getodk/build

Gemfile
Gemfile.lock
README.md
Rakefile
circle.yml
config.ru
config.yml.sample
config_manager.rb
dbconv/README
dbconv/dump_data.rb
dbconv/load_data.sql.erb
model/connection_manager.rb
model/form.rb
model/migrations/001_create_tables.rb
model/migrations/002_add_admin_field.rb
model/migrations/003_rename_login_column.rb
model/migrations/004_add_deleted_at_column.rb
model/migrations/005_add_as_user_audit_column.rb
model/migrations/006_relax_email_constraint.rb
model/user.rb
odkbuild_server.rb
tls_odkbuild.rb
views/index.erb
warden_odkbuild.rb

Please see #87 for the relevant ticket, and the commit messages herein for further detail.

Migrate all code and data from Tokyo* to postgres

---

.gitignore
Gemfile
Gemfile.lock
circle.yml

self-explanatory, other than that we don't need these anymore.

server/noop: remove dependency on tokyo-*.

---

public/javascripts/control.js

* also, reset initial count so we start with 1 again rather than 2.
* fixes #119.

control/bug #119: should take max untitled rather than last untitled #.

---

public/javascripts/i18n.js

i18n/bug #117: should use new lang as display if we have no display lang.

---

server/odkbuild_server.rb

server/bug: erroneously disallowed controlless forms.

---

public/javascripts/dropdown-menu.js

ui/bug #118: clicking on checkmarks in a menu gave undefined behaviour.

---

public/javascripts/application.js
public/javascripts/control.js
public/javascripts/data-ui.js
public/javascripts/i18n.js
public/javascripts/modals.js
public/javascripts/options-editor.js
public/stylesheets/styles.css
server/views/index.erb

The two commits' messages should suffice to explain what happened here. I went for an easier path than either of our initial suggestions.

Delete current selection [#121]

---

public/stylesheets/styles.css
server/views/index.erb

ui/noop #133: add a little advertisement for the offline version.

---

public/javascripts/control.js

* missed one nullcheck.
* resolves #159.

ui/bug #159: NPE on accessing successor property value.

---

public/javascripts/control.js
public/javascripts/property-editor.js

ui/bug #159: more NPE/false-assumption bugs with successor logic.

---

public/javascripts/grid-editor.js
public/javascripts/options-editor.js
public/javascripts/tsv.js
public/stylesheets/styles.css
server/assets.yml
server/views/index.erb

The branch is accidentally numbered #162 but.. whoops. Ignore that.
As of time of PR, still need to test IE. Will update when that is done.

#163 allow bulk copy+paste from spreadsheet into options editor

---

public/javascripts/data.js
public/stylesheets/styles.css
server/views/index.erb

Save, load, XML-export, UI, and help text for:
* instance name
* public key
* submission url
XLSForm-related changes can be found at https://github.com/opendatakit/build2xlsform/commit/14ff48c57ca94fd2b6f65d8d62f2616c474eb07a

Additional form properties

---

public/javascripts/control.js
public/javascripts/core.validation.js
public/javascripts/data.js
public/javascripts/draggable.js
public/javascripts/grid-editor.js
public/javascripts/options-editor.js
public/javascripts/property-editor.js
public/javascripts/tsv.js
public/stylesheets/styles.css
server/assets.yml
server/views/index.erb

This includes all the UI and business logic for cascading selects. This branch is dependent on `cxlt/162`/#163, and so this PR (and its diff) will likely make more sense once PR #174 is merged to `master`.
Comments are available per-commit. Diff is probably more digestible per-commit.
Related: opendatakit/build2xlsform#2

#162 cascading selects

---

public/javascripts/core.validation.js
public/javascripts/data.js

See commit messages for more. Might as well drop this into 0.3.3 I think.

Some minor fixes

---

public/index.html
public/javascripts/control.js
public/javascripts/core.validation.js
public/javascripts/data-ui.js
public/javascripts/data.js
public/javascripts/draggable.js
public/javascripts/grid-editor.js
public/javascripts/impl.validation.js
public/javascripts/options-editor.js
public/javascripts/property-editor.js
public/javascripts/tsv.js
public/stylesheets/styles.css

This includes the new PR #177 just submitted.
Everything merged cleanly and it looks copacetic, so this shouldn't require deep combing.

Merge all changes for 0.3.3 into offline

---

public/javascripts/data.js

* after all that it was this simple.

data/new #195: export ref attributes in group body tags.

---

public/javascripts/control.js
public/javascripts/core.validation.js
public/javascripts/data.js
public/javascripts/impl.validation.js
public/javascripts/property-editor.js
public/stylesheets/styles.css

* apparently long ago when i implemented validations i got partially
done with implementing a warning-level severity but never fully
surfaced it.
* and in particular, the field list expression check was meant to be a
warning, not an error. it's supposed to show, but it's not supposed to
look so scary.
* so here i finish implementing that.

validation/bug #166: finish implementing warning-severity checks.

---

BUILDING.md
server/views/index.erb

Add current maintenance and deployment steps to BUILDING.md

Add deployment docs and update About with links to 0.4.0

---

BUILDING.md

* Add steps necessary to bring the system from supporting 0.3.5 to 0.4.0 to the Deployment section.
* This PR is the last update to the deployment docs and closes #257

Update deployment docs with system upgrade steps

---

public/javascripts/data-ui.js

improve: drop the -export postfix from XLSForm filenames

---

public/javascripts/data-ui.js

noop: Change prompt to save form AS

---

BUILDING.md

A tiny PR to fix the formatting of the last code block in the building document.

fix: code formatting of the last section

---

docker-compose.dev.yml
docker-compose.yml

Use tagged releases on prod and master on dev
