getodk/build

Gemfile, Gemfile.lock, config_manager.rb
* the config.yml file in the source directory is now also optional,
though one of the two are required.
* the /etc file takes precedence over the file in the local source
repository if both are present; the keys are merged in that case.
=> server/new: read optionally from /etc/odkbuild/config.yml for config.

README.md, config.ru, config.yml.sample, tls_odkbuild.rb
* change the cookie_ssl_only setting to true to enable.
* this will turn on:
* secure cookies, meaning HTTPS cookies cannot be read from HTTP.
* HSTS with max-age of 90 days, indicating that for at least 90 days
the site may only be accessed via HTTPS and never from HTTP.
=> server/new: optional secure-cookie/HSTS security.

public/javascripts/property-editor.js, public/stylesheets/styles.css, server/views/index.erb
The css targeting here feels a little messy, so I'm open to suggestions if we don't like this fix.
Also: should 'inclusive' be hidden for 'Select Multiple' fields as well?
=> server/bug #90: hide 'inclusive' form control where N/A

config.ru
Some but not all systems don't seem to serve our static assets. But this line isn't apparently harmful for those systems that do.
=> server/bug: some systems don't automatically serve /public.

public/javascripts/application.js, public/javascripts/data.js, public/javascripts/i18n.js, public/javascripts/options-editor.js, public/javascripts/property-editor.js, server/odkbuild_server.rb, server/views/index.erb
Allows users to type their own language names rather than selecting from the list of ISO-languages, which resolves #55. This PR also fixes #91.
Previously, languages were stored as an array of ISO codes. The strategy here is to move from an array to a hash mapping, and for custom new languages to generate integer codes. So a typical migrated `activeLanguages` databag might look like `{ _counter: 2, _display: "eng", eng: "English", esp: "Spanish", 0: "Cool Language", 1: "Cooler Language" }`. The `_counter` key stores the current increment count for generating integer codes, and the `_display` key keeps track of which language the user has active from the View menu.
As a side effect, the outputted language to XML and to XLSForm is now the full language name rather than a three-letter …
=> Freeform language options

public/javascripts/data-ui.js
* this includes implicit save-as when saving an unsaved form.
* contrary to the description of #63, code audit and testing reveals
that Build does indeed switch to the new form (save as; make change;
save that; reload original and verify it is untouched).
* Fixes #63, Fixes #60.
=> data/bug #63: form name not updated after save-as operation.

public/stylesheets/styles.css
* use (shiny new) css media queries to gracefully degrade as window
narrows:
* first pop the info/prop pane up.
* Then remove the "Add new" text (leave the + icon).
* Finally compress the padding between toolpane buttons.
* Any further and the UI is useless for other reasons.
=> styles/bug: bottom toolpane could get overlapped with narrow windows.

public/javascripts/data-ui.js, server/odkbuild_server.rb
* now produces a helpful error message, and doesn’t throw an exception.
* resolves #107.
=> server/bug #107: unreachable Aggregate URLs produced 500; generic error.

public/javascripts/application.js, public/javascripts/control.js, public/stylesheets/styles.css
* track with a node className rather than a local var, and then apply
css on the className instead.
* was only using the generic toggle/toggleContainer code in one spot, so
eliminate that generic code.
* resolves #138.
=> ui/bug #138: was no longer remembering advanced expansion state.

public/javascripts/control.js
* so enforce a type, like we do elsewhere.
just a little bug i found while testing other things.
=> control/bug: xml export would fail with typeless media control.

playbook.yml
* was configured based off docs to look at
/var/www/letsencrypt/.well-known/...
but the tool writes the challenge file directly to
/var/www/.well-known/...
so we oblige and change nginx to look there.
* also removed a faulty @500 directive.
=> nginx: update letsencrypt root path so that it actually works.

public/javascripts/control.js
* now makes explicit that a custom constraint check failure will trigger
the message.
* select multiple control types now get an Invalid Text property field.
* all control types that don’t have a toplevel Invalid Text field now
automatically have one under advanced just below the custom Constraint
definition field.
* resolves #123.
=> control/new+bug #123: update text and behaviour around Invalid Text.

public/javascripts/application.js, public/javascripts/data-ui.js, public/javascripts/data.js, public/javascripts/modals.js, public/stylesheets/styles.css, server/views/index.erb
* the setting is found in the restored Form Properties dialog, under
the Edit menu.
* the main form title is used if no title-on-phone is given.
* this commit is ugly as hell and full of hacks. but it’s the best i can
do with this codebase.
* resolves #56.
=> export/new #56: allow title-on-phone to differ from title-in-Build.

public/javascripts/data-ui.js, public/stylesheets/styles.css, server/odkbuild_server.rb, server/views/index.erb
Resolves #54.
A bonus commit traps a failure case found during testing of this change, wherein specifying a valid DNS address which fails to respond to :443 or :80 as expected causes a 500. Replaces that with a usefulish error message.
=> Allow upload to HTTP-only Aggregate

server/odkbuild_server.rb
* that was embarrassingly simple.
* resolves #106.
=> server/bug #106: don't throw a 500 if reset password user is NPE.

public/javascripts/control.js, public/javascripts/core.validation.js, public/javascripts/data.js, public/javascripts/impl.validation.js, public/javascripts/property-editor.js, public/stylesheets/styles.css
* also spruce up bindDisplayIf to check against things other than bools.
* also spruce up validation to not validate if the property isn’t shown.
* still need to update opendatakit/build2xlsform for this feature.
=> all/new #157: add range widget.

server/odkbuild_server.rb
This PR aims to fix uploading form to Aggregate via plain (unsecured) HTTP. This is currently not possible as this part of code
https://github.com/opendatakit/build/blob/283da5840c7f83adf8228c558311266723b83fc1/server/odkbuild_server.rb#L252-L255
forces `http.use_ssl = true` every time, resulting in OpenSSL handshake error on plain HTTP.
=> Fix upload to Aggregate via plain (unsecured) HTTP

public/javascripts/draggable.js
* see the lengthy comment for explanation.
* nobody has commented on my open ticket against the chromium project.
=> draggable/bug #214: duplication-drag was broken in safari and chrome.

public/javascripts/data.js
Closes #228
Warning: I have not tried this.
@issa-tseng Our conversation about `instanceID` in the context of Central made me think of this. As you can see, this explains why servers don't have to think too much about `instanceID` collisions -- the IDs are not actually stable across form edit sessions.
As there's talk of better supporting edit workflows and links between forms, stable `instanceID`s become important. This change will happen in `pyxform` soon and since there's a Build release pending, I thought I'd try to squeeze this in at the 23:59th hour...
Feel free to do your own commit if you don't like my commit message or if it's wrong in some way. Or if you'd rather not squeeze something like this in, I understand.
=> improve: use uid preload for stable instanceIDs

server/views/index.erb
updates link to match what is used in the [docs](https://docs.getodk.org/build-intro/#using-odk-build), and gets you to a page that has the download on it instead of just redirecting to the Get ODK homepage
=> update link to fix #250

BUILDING.md
* Fix env vars: first switch user, then set env vars.
* Align both deploy steps (see https://github.com/getodk/build/pull/258#discussion_r765286643).
* Add troubleshooting instructions to revert to older versions.
Merging this PR won't require a new release, as all changes herein are only visible on GitHub.
=> Update deployment docs

public/javascripts/data.js
This patch fixes a bug that was introduced through added support for extras (short label, guidance hint, image labels etc).
This patch has been split out from #266 as requested.
* Closes #268 
* Refactor data.js: pushChildren
* Improve function docs for pushChildren and addTranslation
=> Fix #268: create empty nodes for missing translations

server/views/index.erb
Close #82 
Adds a message to the "About" menu:
=> noop: Add in-app messaging about contributing

public/javascripts/data.js, public/stylesheets/styles.css, server/views/index.erb
Add support to optionally override Collect's autosend and autodelete form management settings.
* Closes #165 
* Form properties (index.erb): add two dropdowns for each setting - empty on legacy forms, three options default, always, never.
* The dropdowns are styled like the other form properties elements (styles.css).
* The form data is plumbed through `data.js` to end up as a child node in the model, tacking onto what `submission_url` does.
* Screenshot 1:  with options always and never, respectively
* Screenshot 2: with option "default" = "Follow ODK Collect settings"
* When loading a new form from "My forms", autosend and autodelete are loaded from that form.
* When exporting to XML with autosend always, autodelete never:
* New namespace `orx`
* New model child `<submission …
=> new: support autosend and autodelete

public/javascripts/data-ui.js
A tiny PR to emit a custom error message when a user forgot to select a form to open.
Other errors at form open output the error to the browser console and advise the user. This might be more informative than the "something's wrong" type generic error, or it might leak sensitive information in cases I haven't thought about - in the latter case we might not want to log the error to the browser console.
=> improve: dedicated error for no form selected in my forms

public/javascripts/control.js, public/javascripts/data.js
This PR breaks the support of `email` out of #284.
* Close #209 (audit is not really a metadata kind as it behaves differently)
* Audit will be addressed in a separate PR as alternative to #284
* Two small changes are added, one to add "email" as available metadata kind, the second to populate the binding.
* The changes are analogous to other metadata kinds, e.g. `username`.
A simple form with a metadata field "email" and a text field:
```
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:orx="http://openrosa.org/xforms" xmlns:odk="http://www.opendatakit.org/xforms">
<h:head>
<h:title>209-email</h:title>
<model> …
```
=> new: support metadata kind email

config.yml.sample, server/views/index.erb
Closes #291 
Totally untested.
=> Switch from configurable GA to hard-coded Fathom

BUILDING.md, server/views/index.erb
Bump version number to reflect the version in the UI.
Note that we are merging to a hot fix branch (0.4.x) not to master.
=> Bump version number

public/javascripts/control.js
* control.js: Do what inputSelectOne does and initiate an empty cascade option.
* This will not fix existing forms.
* Existing forms need to delete the first option of SelectMultiple, then rebuild the options.
* Use `.odkbuild` save file from original issue.
* Drop the SelectMultiple question.
* Create a new SelectMultiple question and add two more options.
* Note: cascading SelectOnes still have the original issue and will not work as expected - underlying values do not match.
* Export to XLSX - works.
* Export to XML - works.
* [SchoolCensusMinimalFix.zip](https://github.com/getodk/build/files/8697843/SchoolCensusMinimalFix.zip): working form as .odkbuild, XML, XLSX.
* See last comment #307 for the same form but fixed with opinionated suggestions
=> Fix #307: Init inputSelectMany with empty cascade option

server/views/index.erb
Closes https://github.com/getodk/build/issues/319
Changes defaults of both autosend and autodelete from the incorrect `"default"` to an empty string `""`.
```
<option value="" selected="selected">Follow ODK Collect settings</option>
```
It appears that my IDE has also deleted some trailing whitespaces.
=> Use empty string as default for autosend and autodelete

server/odkbuild_server.rb
Build was not delivering password resets. Probably because it's sending email from an IP with no DKIM, etc. I've changed the infrastructure to use AWS SES to send emails.
Build's code relies on [Pony](https://github.com/benprew/pony) which relies on sendmail, so after I verified the domain on SES, I followed [send email through SES with sendmail](https://web.archive.org/web/20221111144034/https://docs.aws.amazon.com/ses/latest/dg/send-email-sendmail.html) to configure the server.
I needed to do a hot fix, so this code is already running in production...
=> Use specific domain to increase deliverability

server/views/index.erb
We've deprecated Fathom in favor of CloudFlare across the tools.
This code is already in prod.
=> Replace Fathom with CloudFlare
